#!/usr/bin/env python3
"""
check_public_pii.py — PreToolUse hook (Write|Edit).

Blocks writing a real name / pipeline-target company into a PUBLIC-repo artifact.
The job-search OS repo is public; tests, skill docs, framework docs, and tool
comments are world-readable, so a real contact or target company pasted into a
fixture is a live PII leak (origin: 2026-06-11, real names shipped into
test_outreach_pending.py while building a fix).

Scope (Nick's call, 2026-06-11): TRACKED files only — act on a file only when it is
in a public path AND not gitignored. Private data (data/**), the gitignored denylist,
scan caches, and the in-repo ./memory copy are all skipped.

Detection is deterministic: a case-sensitive whole-word/phrase match against the
gitignored denylist (tools/.pii-denylist.txt, generated by gen_pii_denylist.py).
The denylist holds only DISTINCTIVE tokens (full names + brand-name companies); the
semantic catch-all for new/ambiguous names is the /audit-pii subagent pass at commit
time. So this hook is intentionally high-precision, not high-recall.

Exit 2 = block. Any other path = allow. Fails OPEN on any error.

Triggered by .claude/settings.json PreToolUse hook on Write|Edit.
"""
import json
import os
import re
import subprocess
import sys
from pathlib import Path

DENYLIST_REL = "tools/.pii-denylist.txt"
AMBIGUOUS_REL = "tools/.pii-denylist-ambiguous.txt"

# Public-repo path prefixes/globs. A file outside these is not a public artifact.
# examples/ + plugins/ are tracked public surface too (fable-audit 2026-07-07 #10/#17).
PUBLIC_PREFIXES = ("tests/", ".claude/skills/", "framework/", "docs/", "examples/", "plugins/")
# Plus: tools/*.{py,md,sh} and top-level *.md (README.md, CLAUDE.md, ...).

# Binary / non-text extensions: never text-scanned for denylist tokens. A PDF's byte
# stream can contain a short denylist brand-token as a substring and false-positive,
# which would block every push once examples/ (which ships a sample-CV PDF) is in
# scope (fable-audit 2026-07-07 #18).
BINARY_EXTS = frozenset({
    "pdf", "png", "jpg", "jpeg", "gif", "ico", "bmp", "webp",
    "zip", "gz", "tar", "woff", "woff2", "ttf", "otf", "eot",
    "pyc", "pkl", "db", "sqlite", "xlsx", "docx", "pptx",
})


def is_binary(rel: str) -> bool:
    ext = rel.rsplit(".", 1)[-1].lower() if "." in rel else ""
    return ext in BINARY_EXTS


def is_public_path(rel: str) -> bool:
    if rel.startswith("data/"):
        return False
    if any(rel.startswith(p) for p in PUBLIC_PREFIXES):
        return True
    if rel.startswith("tools/") and rel.rsplit(".", 1)[-1] in ("py", "md", "sh"):
        return True
    if "/" not in rel and rel.endswith(".md"):  # top-level markdown
        return True
    return False


def is_gitignored(root: Path, rel: str) -> bool:
    """True if git ignores the path. Fails toward False (scan) when git is unavailable,
    so the public-path glob still protects the surface."""
    try:
        r = subprocess.run(
            ["git", "-C", str(root), "check-ignore", "-q", rel],
            capture_output=True, timeout=5,
        )
        return r.returncode == 0
    except Exception:
        return False


def load_denylist(root: Path) -> list[str]:
    try:
        lines = (root / DENYLIST_REL).read_text(encoding="utf-8").splitlines()
    except (FileNotFoundError, PermissionError):
        return []
    return [ln.strip() for ln in lines if ln.strip() and not ln.startswith("#")]


def load_ambiguous(root: Path) -> list[str]:
    """WARN-tier tokens. Missing file = empty list (fail open, same as the block tier)."""
    try:
        lines = (root / AMBIGUOUS_REL).read_text(encoding="utf-8").splitlines()
    except (FileNotFoundError, PermissionError):
        return []
    return [ln.strip() for ln in lines if ln.strip() and not ln.startswith("#")]


def find_pii(content: str, tokens: list[str]) -> list[str]:
    """Case-sensitive whole-word/phrase matches. The trailing/leading \\w boundaries
    keep a short brand token from matching inside a longer word (e.g. 'Zorp' must not
    fire on 'Zorped', and a word like 'Front' must not fire on 'frontmatter')."""
    hits = []
    for tok in tokens:
        pattern = r"(?<![\w])" + re.escape(tok) + r"(?![\w])"
        if re.search(pattern, content):
            hits.append(tok)
    return hits


def main():
    try:
        data = json.load(sys.stdin)
    except Exception:
        return

    tool_name = data.get("tool_name", "")
    tool_input = data.get("tool_input", {}) or {}
    file_path = tool_input.get("file_path", "")
    if not file_path:
        return

    # Derive repo root from this file's location (tools/), not cwd() — the hook
    # runs with an absolute script path, so __file__ is reliable even when the
    # session is launched from outside the repo root. (fable-audit 2026-07-07 #3)
    # PII_REPO_ROOT overrides for tests, which inject a fixture repo + denylist.
    root_env = os.environ.get("PII_REPO_ROOT")
    root = Path(root_env).resolve() if root_env else Path(__file__).resolve().parent.parent
    try:
        rel = os.path.relpath(os.path.abspath(file_path), root)
    except Exception:
        return
    if rel.startswith(".."):  # outside the repo
        return

    rel = rel.replace(os.sep, "/")
    if not is_public_path(rel) or is_gitignored(root, rel):
        return
    if is_binary(rel):
        return  # never text-scan binary blobs (a PDF byte stream false-positives, #18)

    if tool_name == "Write":
        content = tool_input.get("content", "")
    elif tool_name == "Edit":
        content = tool_input.get("new_string", "")
    else:
        return

    tokens = load_denylist(root)
    if not tokens:
        return  # fail open — no denylist, nothing to enforce

    hits = find_pii(content, tokens)

    # WARN tier (added 2026-08-10). Single-token company names that are also ordinary
    # English words are excluded from the BLOCK list above, because matching them would
    # false-positive on prose. Excluding them entirely is what let a live pipeline
    # company reach six public files on 2026-08-10 while all three of its interviewers
    # were correctly blocked. So: surface, never block. Per feedback_warn_vs_block_hook_design.
    amb_hits = find_pii(content, load_ambiguous(root))
    if amb_hits and not hits:
        uniq_amb = sorted(set(amb_hits))
        print(
            f"WARN: {Path(file_path).name} contains token(s) that match a pipeline company "
            f"name which is also an ordinary word: {', '.join(uniq_amb)}.\n"
            "Not blocking — this is very often a false positive. But if any of these refers "
            "to the real company, replace it with a placeholder (ActiveCo / ClosedCo / Acme) "
            "before committing. Ambiguous tier: tools/.pii-denylist-ambiguous.txt",
            file=sys.stderr,
        )

    if not hits:
        return

    name = Path(file_path).name
    uniq = sorted(set(hits))
    msg = [
        f"BLOCKED: {name} is a public-repo artifact and the content contains real PII.",
        "",
        f"Matched denylisted token(s): {', '.join(uniq)}",
        "",
        "The job-search OS repo is PUBLIC. Real contacts and pipeline/target companies",
        "must never appear in tests, skill docs, framework docs, or tool comments.",
        "",
        "Fix: replace each with a generic placeholder that preserves the example's intent",
        "(people: Casey Doe / Jordan Sample / Alex Example; companies: ClosedCo / ActiveCo /",
        "LiveCo / Acme). Keep only the keyword the logic actually tests.",
        "",
        "Rule: feedback_generalize_examples_in_public_artifacts. If this is a false positive",
        "(the token is genuinely generic here), log it:",
        f"  PYTHONIOENCODING=utf-8 python3 tools/friction_log.py append check_public_pii.py \"FP: {uniq[0]}\"",
    ]
    print("\n".join(msg), file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as e:
        print(f"check_public_pii.py error (allowing through): {e}", file=sys.stderr)
