#!/usr/bin/env python3
"""
check_prep_doc_format.py — PreToolUse hook. Blocks the two prep-doc defects that are
mechanically decidable from the text alone.

SCOPE IS THE WHOLE DESIGN. `check_prep_doc.py` runs six checks; only two of them belong
at hook tier, and getting that boundary wrong is how a hook becomes something everyone
routes around:

  BLOCKED here (context-free, single correction, always wrong):
    1. An `<!-- outreach_status: ... -->` stamp that is malformed or not tool_version=2.
       A stamp is machine-generated by `outreach_status.py --stamp`, which only ever
       emits v2 — so a bad one means someone hand-edited it, and the fix is always
       "regenerate it." No context can make a v1 stamp correct.
    2. Primary and Reserve proof domains that are invalid, or that CANONICALIZE to the
       same domain. Only fires when BOTH lines are present, so it never blocks a doc
       mid-authoring. Two labels for one domain is not a fallback; one exclusion
       sentence takes out both proofs.

  NOT blocked here — left to `check_prep_doc.py` Step 6a and the skill instructions:
    * A MISSING reserve proof (checks 1/2). Mid-authoring a doc legitimately has only a
      primary; blocking that would fire on every normal write.
    * Suppressive phrasing without a delivery stamp (check 4). Contextual: "already
      sent" is only a defect when unbacked, and deciding that needs the outreach log.
    * A stale stamp (check 5). Needs the doc's intended date, which an in-flight Write
      does not reliably carry.

Per `feedback_warn_vs_block_hook_design` and tools/HOOK_AUTHORING.md: a PreToolUse
"warn" (exit 0 + stderr) is NOT surfaced by Claude Code, so there is no soft tier. A
hook either blocks (exit 2) or is invisible. Everything above that is not
always-wrong therefore stays out of this file.

NOTE ON `hook_command_lint.strip_literals`: deliberately NOT used. That module solves
the command-position-not-substring problem for **Bash** hooks scanning a command string.
This hook reads file CONTENT, where there is no shell syntax to mis-parse. The
equivalent false-positive risk here is path scope (docs *about* prep docs), handled by
_is_prep_doc below.

Fails open (exit 0) on anything unexpected — bad JSON, missing path, unreadable content.
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import check_prep_doc  # noqa: E402  (parse_stamps + the frozen stamp regex)
import prep_doc_parse  # noqa: E402  (parse_proofs_text + the frozen proof regex)
import proof_domains  # noqa: E402  (canonicalize)

# A prep doc is `output/<company-slug>/<...>prep<...>.md`. Everything else is out of
# scope, including docs that merely DISCUSS the format.
_PREP_PATH_RE = re.compile(r"(^|/)output/[^/]+/[^/]*prep[^/]*\.md$", re.I)

# Paths that look like prep docs but are not. Each is a real false-positive source:
#   tests/  -> tests/fixtures/w4/output/acme-corp/081026-prep.md and the deliberately
#              malformed-stamp fixtures. A hook that blocks its own test fixtures makes
#              the suite unrunnable.
#   output/analysis/ -> specs, build logs and audits quote stamps and proof lines as
#              examples; they are prose about the format, not instances of it.
_EXCLUDED_RE = re.compile(r"(^|/)(tests|node_modules|\.git)/|(^|/)output/analysis/", re.I)


def _is_prep_doc(path: str) -> bool:
    normalized = (path or "").replace(os.sep, "/")
    if not normalized or _EXCLUDED_RE.search(normalized):
        return False
    return bool(_PREP_PATH_RE.search(normalized))


def _block(lines: list[str]) -> int:
    print("BLOCKED: prep-doc format violation (check_prep_doc_format.py)", file=sys.stderr)
    for line in lines:
        print(line, file=sys.stderr)
    print(
        "\nIf this block is wrong, log it now — it is the only telemetry for a false "
        "positive:\n  PYTHONIOENCODING=utf-8 python3 tools/friction_log.py append "
        'check_prep_doc_format.py "FP: <what got wrongly blocked>"',
        file=sys.stderr,
    )
    return 2


def check_content(text: str) -> list[str]:
    """Return block reasons for `text`. Empty list means clean."""
    problems: list[str] = []

    # --- 1. stamp format
    _, malformed = check_prep_doc.parse_stamps(text)
    for raw in malformed:
        problems.append(
            f"  - Malformed outreach_status stamp: {raw}\n"
            f"    Expected the frozen v{check_prep_doc.EXPECTED_TOOL_VERSION} format with an "
            f"`artifact=` field. Never hand-edit a stamp — regenerate it:\n"
            f"      PYTHONIOENCODING=utf-8 python3 tools/outreach_status.py --recipient "
            f'"<name>" --artifact <token> --as-of <YYYY-MM-DD> --stamp'
        )

    # --- 2. proof domains, only when BOTH lines are present
    proofs = prep_doc_parse.parse_proofs_text(text)
    if proofs["primary"] and proofs["reserve"]:
        canon = {}
        for slot in ("primary", "reserve"):
            tag = proofs[slot]["tag"]
            resolved = proof_domains.canonicalize(tag)
            if resolved is None:
                problems.append(
                    f"  - {slot.capitalize()} domain tag '{tag}' is not in the closed enum.\n"
                    f"    Valid tags: {', '.join(proof_domains.valid_tags())}\n"
                    f"    Resolve it: PYTHONIOENCODING=utf-8 python3 tools/proof_domains.py "
                    f"--canonicalize '{tag}'"
                )
            canon[slot] = resolved
        if canon.get("primary") and canon.get("primary") == canon.get("reserve"):
            problems.append(
                f"  - Primary '{proofs['primary']['tag']}' and reserve "
                f"'{proofs['reserve']['tag']}' both canonicalize to '{canon['primary']}'.\n"
                f"    That is one domain wearing two labels, not a fallback — a single "
                f"exclusion sentence takes out both proofs.\n"
                f"    Pick a genuinely different domain; do NOT relabel the same proof."
            )

    return problems


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except Exception:
        return 0  # fail open

    tool_input = data.get("tool_input") or {}
    if not _is_prep_doc(tool_input.get("file_path", "")):
        return 0

    tool_name = data.get("tool_name", "")
    if tool_name == "Write":
        text = tool_input.get("content", "")
    elif tool_name in ("Edit", "MultiEdit"):
        # An Edit carries a FRAGMENT, not the whole doc. Both checks stay correct on a
        # fragment: a malformed stamp is malformed in isolation, and the domain check
        # only fires when both proof lines are present in the same payload.
        text = tool_input.get("new_string", "")
    else:
        return 0

    if not isinstance(text, str) or not text.strip():
        return 0

    problems = check_content(text)
    return _block(problems) if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
