#!/usr/bin/env python3
"""Generate the memory-hygiene handoff's state block from a live scan.

WHY THIS EXISTS. Rev 6 of `output/analysis/081326-memory-hygiene-HANDOFF.md` stated
"backlog 40 of 432". That number was produced by incrementing rev 4's figure by hand,
one screen below rev 6's own instruction to re-measure. Live at the time: 66 of 488.
That was the 3rd fire of `feedback_remeasure_state_before_trusting_a_handoff`, and the
tier lesson is that a prose warning cannot stop the author of that prose from typing a
number, because the warning addresses the reader while the defect is committed by the
writer.

So the numbers stop being typed. This module is the single source of truth for the
block, `--write` puts it in the doc, and `tests/scripts/test_handoff_state_block.py`
fails when the doc disagrees with a fresh scan. Check tier, not prose tier.

Usage:
  PYTHONIOENCODING=utf-8 python3 tools/handoff_state.py            # print the block
  PYTHONIOENCODING=utf-8 python3 tools/handoff_state.py --write    # update the handoff
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
HANDOFF = REPO_ROOT / "output" / "analysis" / "081326-memory-hygiene-HANDOFF.md"
BEGIN = "<!-- STATE-BLOCK:BEGIN -- generated by tools/handoff_state.py, do not hand-edit -->"
END = "<!-- STATE-BLOCK:END -->"
FIELDS = ("promotion_backlog", "promotion_total", "partial", "terminal",
          "needs_review", "oversized_context_files")


def scan(repo_root: Path = REPO_ROOT) -> dict:
    """Run attention.py and lift the promotion queue out of it."""
    proc = subprocess.run(
        [sys.executable, str(repo_root / "tools" / "attention.py"),
         "--json", "--repo-root", str(repo_root)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"attention.py failed: {proc.stderr[:400]}")
    data = json.loads(proc.stdout)
    q = next((q for q in data["queues"] if q["name"] == "promotion"), None)
    if q is None:
        raise RuntimeError("attention.py reported no 'promotion' queue")
    d = q.get("detail") or {}
    missing = [k for k in ("partial", "terminal", "needs_review") if k not in d]
    if missing:
        raise RuntimeError(f"promotion queue is missing {missing}; schema changed")
    return {
        "promotion_backlog": q["count"],
        "promotion_total": q["denominator"],
        "partial": d["partial"],
        "terminal": d["terminal"],
        "needs_review": d["needs_review"],
        "oversized_context_files": d.get("oversized_context_files", 0),
        "date": data["date"],
    }


def state_block(repo_root: Path = REPO_ROOT) -> str:
    s = scan(repo_root)
    lines = [BEGIN, f"generated: {s['date']} by tools/handoff_state.py"]
    lines += [f"{k}: {s[k]}" for k in FIELDS]
    lines.append(END)
    return "\n".join(lines)


def write(repo_root: Path = REPO_ROOT) -> str:
    block, path = state_block(repo_root), HANDOFF
    text = path.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        text = head + block + tail
    else:
        anchor = "\n## What changed at rev 7"
        if anchor not in text:
            raise RuntimeError("no STATE-BLOCK and no anchor to insert one before")
        text = text.replace(anchor, "\n" + block + "\n" + anchor, 1)
    path.write_text(text, encoding="utf-8")
    return block


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--write", action="store_true", help="update the handoff in place")
    args = ap.parse_args(argv)
    print(write() if args.write else state_block())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
