#!/usr/bin/env python3
"""
n8n_weekly_reminder.py — Write weekly review reminder to inbox/.

Run by n8n "Weekly Review Reminder" workflow every Friday at 4pm.
Writes a single prompt to inbox/ so it surfaces in /standup or /act.

Usage:
  PYTHONIOENCODING=utf-8 python tools/n8n_weekly_reminder.py [--repo-root PATH]
"""
import argparse
from datetime import date
from pathlib import Path


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--repo-root", default=None)
    args = p.parse_args()

    repo_root = Path(args.repo_root).resolve() if args.repo_root else Path(__file__).parent.parent

    today = date.today()
    inbox = repo_root / "inbox"
    inbox.mkdir(exist_ok=True)

    lines = [
        f"# Weekly Review Reminder — {today.isoformat()}",
        "",
        "It's Friday — time to run your weekly job search retrospective.",
        "",
        "→ Run `/weekly-review` to generate this week's review.",
        "",
        "Covers: pipeline health · outreach response rates · task velocity · top 5 priorities for next week.",
        "",
        "_Auto-generated by n8n (Friday 4pm)._",
        "",
    ]

    out_path = inbox / f"{today.strftime('%Y%m%d')}-weekly-review-reminder.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path.name}")


if __name__ == "__main__":
    main()
