#!/usr/bin/env python3
"""Generic probe runner for the workstreams registry (`data/workstreams/*.md`).

WHY THIS EXISTS. `tools/handoff_state.py` proved the mechanism -- numbers stop being typed,
a generated block is the source of truth, and a drift test fails when the doc disagrees with
a fresh scan -- but it hardcodes one handoff path, one scan, and one field schema. Every
workstream wants the identical answer to "run my probe, show the number", so the runner is
MECHANISM and belongs in one tested module; what the number MEANS is POLICY and stays in the
per-workstream file.

This module REPLACES handoff_state.py once memory-hygiene state is migrated into its
workstream file. Two generators for the same state is the defect, not the fix.

CONTRACT (output/analysis/091426-workstreams-build-spec.md, D1 and D3):

  * A workstream declares its probe as an argv LIST, or as an OBJECT when the tool needs
    policy attached:
        <!-- PROBE: ["python3", "tools/scan_promotion_candidates.py", "--json"] -->
        <!-- PROBE: {"argv": [...], "field": "violations", "ok_exit": [0, 1]} -->
    An argv list, never a shell string. A free-text command line in Markdown is an
    executable program embedded in data.
  * The probe prints JSON; the workstream declares which field to lift (default `value`).
    `field`, `ok_exit` and `text` are POLICY and live in the workstream file, because the
    real tools share no output convention -- `scoring_probe.py` exits 1 when it finds
    violations, which is its NORMAL state, and `check_hook_warn_tier.py` prints a line
    rather than JSON. A contract that ignored that would have been written against
    fixtures instead of the tools it has to run.
  * An exit code outside `ok_exit`, a timeout, unparseable stdout, a missing field, or
    oversized output are all `error` -- and `error` NEVER collapses to `unchanged` or to 0.
    That collapse is the defect this contract exists to prevent: a broken probe would make
    a workstream go quiet, which reads exactly like a workstream that is fine.
  * A workstream with NO probe is `typed`, which is a legitimate state and distinct from a
    probe that failed. Coverage is not uniform and must not pretend to be.
  * `terminal` is excluded from the count entirely.

  * `changed` ::= current != last_surfaced. The last-surfaced store
    (`data/workstreams/.observations.json`) is advanced ONLY by a successful render, never
    by this module. If a render crashes, the next run re-surfaces: the failure direction is
    "shown twice", never "silently dropped".

Usage:
  PYTHONIOENCODING=utf-8 python3 tools/workstream_state.py            # report, no writes
  PYTHONIOENCODING=utf-8 python3 tools/workstream_state.py --render   # update STATE-BLOCKs
  PYTHONIOENCODING=utf-8 python3 tools/workstream_state.py --json
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY = REPO_ROOT / "data" / "workstreams"
OBSERVATIONS = ".observations.json"

BEGIN = "<!-- STATE-BLOCK:BEGIN -- generated by tools/workstream_state.py, do not hand-edit -->"
END = "<!-- STATE-BLOCK:END -->"

PROBE_RE = re.compile(r"<!--\s*PROBE:\s*([\[{].*?[\]}])\s*-->", re.S)
STATUS_RE = re.compile(r"\|\s*\*\*Status\*\*\s*\|\s*([A-Za-z-]+)", re.I)

DEFAULT_TIMEOUT = 120.0
DEFAULT_MAX_BYTES = 256 * 1024
STALE_DAYS = 30


class MarkerError(RuntimeError):
    """The STATE-BLOCK markers are missing a partner, or duplicated."""


def _parse_probe(text: str) -> dict | None:
    """Parse a PROBE declaration into a spec dict, or None if absent/malformed.

    Two accepted forms. The list form is the common case:

        <!-- PROBE: ["python3", "tools/scoring_probe.py", "--json"] -->

    The object form carries the POLICY a given tool needs, because the real tools do not
    share one output convention and pretending they do was the defect (2026-09-14: the
    first contract required a `value` field and exit 0, which `scoring_probe.py` violates
    by design -- it exits 1 when it finds violations, which is its NORMAL state):

        <!-- PROBE: {"argv": [...], "field": "violations", "ok_exit": [0, 1]} -->

      field    dotted path to lift from the JSON. Default "value".
      ok_exit  exit codes that mean the probe RAN. Default [0]. Anything else is `error`.
      text     true if the probe prints a line rather than JSON; the line becomes the value.
    """
    m = PROBE_RE.search(text)
    if not m:
        return None
    try:
        raw = json.loads(m.group(1))
    except json.JSONDecodeError:
        return None
    if isinstance(raw, list):
        raw = {"argv": raw}
    if not isinstance(raw, dict):
        return None
    argv = raw.get("argv")
    if not isinstance(argv, list) or not argv or not all(isinstance(a, str) for a in argv):
        return None
    ok_exit = raw.get("ok_exit", [0])
    if not isinstance(ok_exit, list) or not all(isinstance(c, int) for c in ok_exit):
        return None
    return {"argv": argv, "field": raw.get("field", "value"),
            "ok_exit": ok_exit, "text": bool(raw.get("text", False))}


def _lift(data, path: str):
    """Lift a dotted path out of parsed JSON. Raises KeyError if absent."""
    cur = data
    for part in path.split("."):
        if not isinstance(cur, dict) or part not in cur:
            raise KeyError(path)
        cur = cur[part]
    return cur


def _parse_status(text: str) -> str:
    m = STATUS_RE.search(text)
    return (m.group(1) if m else "ACTIVE").upper()


def _run_probe(spec: dict, repo_root: Path, timeout: float, max_bytes: int) -> dict:
    """Run one probe under the D3 contract. Never raises; returns a state dict."""
    argv = [sys.executable if a == "python3" else a for a in spec["argv"]]
    env = {**os.environ, "PYTHONIOENCODING": "utf-8"}
    try:
        proc = subprocess.run(
            argv, cwd=str(repo_root), capture_output=True, text=True,
            timeout=timeout, env=env,
        )
    except subprocess.TimeoutExpired:
        return {"state": "error", "error": f"probe exceeded {timeout}s"}
    except (OSError, ValueError) as exc:
        return {"state": "error", "error": f"probe could not start: {exc}"}
    if proc.returncode not in spec["ok_exit"]:
        return {"state": "error",
                "error": f"exit {proc.returncode} (ok_exit={spec['ok_exit']}): "
                         f"{(proc.stderr or '').strip()[:240]}"}
    out = proc.stdout or ""
    if len(out.encode("utf-8", "replace")) > max_bytes:
        return {"state": "error", "error": f"probe output exceeded {max_bytes} bytes"}
    if spec["text"]:
        line = out.strip().splitlines()[0] if out.strip() else ""
        if not line:
            return {"state": "error", "error": "probe declared text mode but printed nothing"}
        return {"state": "ok", "value": line}
    try:
        data = json.loads(out)
    except json.JSONDecodeError:
        return {"state": "error", "error": f"probe stdout is not JSON: {out.strip()[:200]}"}
    try:
        return {"state": "ok", "value": _lift(data, spec["field"])}
    except KeyError:
        return {"state": "error",
                "error": f"probe JSON has no `{spec['field']}` (schema changed?)"}


def _load_observations(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def evaluate(ws_path: Path, *, repo_root: Path = REPO_ROOT, observations: dict | None = None,
             timeout: float = DEFAULT_TIMEOUT, max_bytes: int = DEFAULT_MAX_BYTES) -> dict:
    """Evaluate ONE workstream. Pure with respect to the ack store -- never writes it."""
    name = ws_path.stem
    text = ws_path.read_text(encoding="utf-8")
    status = _parse_status(text)
    row: dict = {"name": name, "path": str(ws_path), "status": status}

    if status == "TERMINAL":
        return {**row, "state": "terminal", "surfaces": False}

    spec = _parse_probe(text)
    if spec is None:
        row["state"] = "typed"
        row["surfaces"] = False  # only a staleness check can raise a typed row
        return row

    result = _run_probe(spec, repo_root, timeout, max_bytes)
    if result["state"] == "error":
        return {**row, "state": "error", "error": result["error"], "surfaces": True}

    if observations is None:
        observations = _load_observations(ws_path.parent / OBSERVATIONS)
    prior = (observations or {}).get(name)
    value = result["value"]
    changed = prior is None or prior.get("value") != value
    return {**row, "state": "changed" if changed else "unchanged",
            "value": value, "previous": (prior or {}).get("value"),
            "surfaces": changed}


def state_block(row: dict) -> str:
    stamp = _dt.date.today().isoformat()
    lines = [BEGIN, f"generated: {stamp} by tools/workstream_state.py",
             f"state: {row['state']}"]
    if "value" in row:
        lines.append(f"value: {json.dumps(row['value'])}")
    if row.get("error"):
        lines.append(f"error: {row['error']}")
    lines.append(END)
    return "\n".join(lines)


def _splice(text: str, block: str) -> str:
    begins, ends = text.count(BEGIN), text.count(END)
    if begins != ends or begins > 1:
        raise MarkerError(f"expected 0 or 1 matched STATE-BLOCK pair, found {begins}/{ends}")
    if begins == 0:
        return text.rstrip("\n") + "\n\n" + block + "\n"
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + block + tail


def _atomic_write(path: Path, text: str) -> None:
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def render(ws_path: Path, *, repo_root: Path = REPO_ROOT, **kw) -> dict:
    """Evaluate one workstream and write its STATE-BLOCK. Does NOT advance the ack."""
    row = evaluate(ws_path, repo_root=repo_root, **kw)
    text = ws_path.read_text(encoding="utf-8")
    _atomic_write(ws_path, _splice(text, state_block(row)))
    return row


def acknowledge(obs_path: Path, values: dict) -> None:
    """Advance last-surfaced. Called ONLY after a successful render to a human."""
    now = _dt.datetime.now().isoformat(timespec="seconds")
    data = _load_observations(obs_path)
    for name, value in values.items():
        data[name] = {"value": value, "at": now}
    _atomic_write(obs_path, json.dumps(data, indent=2, sort_keys=True) + "\n")


def scan_registry(registry: Path = REGISTRY, *, repo_root: Path = REPO_ROOT, **kw) -> list[dict]:
    files = sorted(p for p in registry.glob("*.md") if not p.name.startswith("."))
    observations = kw.pop("observations", None)
    if observations is None:
        observations = _load_observations(registry / OBSERVATIONS)
    return [evaluate(p, repo_root=repo_root, observations=observations, **kw) for p in files]


def summary(rows: list[dict]) -> dict:
    surfacing = [r for r in rows if r.get("surfaces")]
    return {
        "total": len(rows),
        "surfacing": len(surfacing),
        "changed": sum(1 for r in rows if r["state"] == "changed"),
        "error": sum(1 for r in rows if r["state"] == "error"),
        "typed": sum(1 for r in rows if r["state"] == "typed"),
        "terminal": sum(1 for r in rows if r["state"] == "terminal"),
        "names": [r["name"] for r in surfacing],
    }


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--render", action="store_true", help="write each STATE-BLOCK in place")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--registry", type=Path, default=REGISTRY)
    ap.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    args = ap.parse_args(argv)

    if args.render:
        files = sorted(p for p in args.registry.glob("*.md") if not p.name.startswith("."))
        rows = [render(p, repo_root=args.repo_root) for p in files]
    else:
        rows = scan_registry(args.registry, repo_root=args.repo_root)

    s = summary(rows)
    if args.json:
        print(json.dumps({"summary": s, "rows": rows}, indent=2))
    else:
        for r in rows:
            extra = r.get("error") or (f"value={r.get('value')}" if "value" in r else "")
            print(f"  {r['state']:9} {r['name']:32} {extra}")
        print(f"\n{s['surfacing']} of {s['total']} surfacing "
              f"(changed {s['changed']}, error {s['error']}, "
              f"typed {s['typed']}, terminal {s['terminal']})")
    return 1 if s["error"] else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
